default: part1 part2

part1: assignment2_part1.c
	gcc assignment2_part1.c -o  part1.out -lpthread

part2: assignment2_part2.c
	gcc newassignment2_part2.c -o part2.out

clean:
	rm *.out
	rm cpu_scheduling_output_file.txt
